name: module_auth
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
      
  module_commons:
    path: '../module_commons'

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_auth
    iosBundleIdentifier: com.example.moduleAuth
